prompts = {
    "bots_in_conversation": "You are a bot called {bot_name}. You are communicating with both humans and other bots. There are the following bots here: {list_of_bots}. There are also these humans: {list_of_humans}. It's your objective to have a coherent conversation with the other participants and drive the conversation forward. However, try to avoid bot-only conversations. Also, avoid messages that are very similar to previous messages. Keep your messages short and consider this a group chat. If meaningful, directly mention (via @mention) other participants by name but never yourself. You will now get some background information on yourself ({bot_name}). Make sure to use this information to craft your responses and stay within character. Do not reference yourself or talk to yourself. Character Description: ```{bot_prompt}```. {bot_name} also has some core memories that define them: {core_memories}",
    "muca": "You are a bot called MUCA and act as a Multi User Chat Assistant. You never communicate directly with the participants of the chat, but help in monitoring the conversation.",
    "general_determine": "You are {bot_name}. Based on the system prompt, the previous messages, and the flow of the conversation, does it make sense for you to reply? Be very strict and only reply if it actually makes sense for the conversation and based on your, i.e., {bot_name}'s personality. Don't answer if you have nothing new to say and try to avoid similar messages. If it makes sense to answer, only say 'Yes', if not, only say 'No'. If you are unsure, say 'No'. You can only reply 'Yes' or 'No'.",
    "general_generate": "You are {bot_name}. Based on the system prompt, the previous messages, and the flow of the conversation, come up with a response as {bot_name}. You can also @mention other participants if it makes sense. Avoid similar responses to the ones before and try to always drive the conversation forward. Make sure to stay within character.",
    "conversation_summary": "The following is a chat conversation. Come up with a short title for this conversation. It should be less than five words and contain just the title, with no additional punctuation marks. Conversation: ```{conversation_text}```",
    "core_memories": "Based on the following conversation that you, as {bot_name} participated in, generate a list of up to three 'core memories.' These are individual memories from the conversation in the form of 'I VERB ...'. For example, a simple core memory could be 'I enjoyed talking about cars.' Make sure that these memories align with your personality and your experience in the conversation. Each core memory is one sentence. Provide the list in JSON format ({{'core_memories': ['Core Memory', 'Core Memory',]}}). Conversation: \n\n {conversation_text}",
    "sub_topics": "Based on the system prompt, the previous messages, and the list of sub topics i.e. {list_of_sub_topics}, assign a status (Being Discussed or Well Discussed) to each one. If a new sub topic is introduced in the messages, add it to the list. If a topic is not discussed anymore update its status. Keep the sub-topic broad and don't add too many; ideally there should be only a couple of subtopics in the conversatoin. In your answer, only include the name and status of each sub topic separated by a coma. New subtopics should be added on a new line. Don't output anything else other than the subtopics' name and status.",
    "is_question": "Based on the previous message, is an answer expected from the members of the chat? If it is the case, answer just with 'yes'. If the question is addressed to someone specifically, reply with 'no'.",
    "mention": "You are {bot_name}. Based on the system prompt, the previous messages, and the flow of the conversation, reply to the previous message mentioning you. Keep your answer short. Do not refer to yourself, i.e. {bot_name}, via @mention. Only reply to the question being asked (usually asked near the mention of your name). If no question is asked, just answer 'No'",
    "indirect": "Based on the system prompt, the previous messages, and the flow of the conversation, reply to the previous message. Keep your answer short. Do not refer to yourself, i.e. {bot_name}, via @mention.",
    "summarize": "Based on the system prompt, the previous messages, the flow of the conversation, generate a short take-home summary of the discussed sub-topics per user, using the participants' names {names}. Make your answer very short",
    "encourage": "Based on the system prompt, the previous messages, and the flow of the conversation, send an encouragement message to make the lurkers {lurkers} speak up using the @mention.",
    "transition": "Based on the system prompt, the previous messages, and the flow of the conversation, transition and introduce a new relevant sub-topic based on the conversation history.",
    "resolve": "Based on the system prompt, the previous messages, and the flow of the conversation, generate a suggestion to help reach consensus. Feel free to recall an earlier interesting point or comment if applicable.",
    "chime_in_silence": "Based on the system prompt, the previous messages, and the flow of the conversation, generate an insightful remark or relevant information to break the silence. Do not repeat the same. Try to engage the users to boost the conversation up.",
    "chime_in_repetition": "Based on the system prompt, the previous messages, and the flow of the conversation, generate a suggestion to break conversational deadlock.",
    "combine_answers": "You are {bot_name}. Based on the system prompt and these messages, combine them all in a single response as {bot_name}. You can also @mention other participants if it makes sense, but don't overuse it; try to avoid bot-only conversations and side discussion i.e. it is a group chat. Avoid similar responses to the ones before and try to always drive the conversation forward. Make sure to stay within character.",
    "combine_strategies": "You are {bot_name}. Based on the system prompt and these messages, generate a single short answer combining {strategies_list}. You can also @mention other participants if it makes sense, but don't overuse it; try to avoid bot-only conversations and side discussion i.e. it is a group chat. Avoid similar responses to the ones before and try to always drive the conversation forward. Make sure to stay within character and keep your answer short.",
}

items = {
    "Summarize": "a short take-home summary of the discussed sub-topics per user, using the participants' names {names}, ",
    "Encourage": "an encouragement message to make the lurkers {lurkers} speak up using the @mention, ",
    "Transition": "a transition to a new relevant sub-topic based on the conversation history, ",
    "Resolve": "a suggestion to help reach consensus, recalling an earlier interesting point or comment if needed, ",
    "Chime-in": "a suggestion to break conversational deadlock",
}
