# Generated by Django 5.1.1 on 2025-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_bot_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not discussed', 'Not Discussed'), ('being discussed', 'Being Discussed'), ('well discussed', 'Well Discussed')], max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sub_topics',
            field=models.ManyToManyField(related_name='conversations', to='chat.subtopic'),
        ),
    ]
