# Generated by Django 5.1.1 on 2025-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_subtopic_conversation_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='status',
            field=models.CharField(choices=[('being discussed', 'Being Discussed'), ('well discussed', 'Well Discussed')], max_length=25),
        ),
    ]
