# Generated by Django 5.1.1 on 2025-04-22 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_subtopic_id_alter_subtopic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='sub_topics',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='chat.conversation'),
        ),
    ]
