# Generated by Django 5.1.1 on 2025-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_conversation_sub_topics_subtopic_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
