# Generated by Django 5.1.1 on 2025-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_subtopic_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
