# Generated by Django 5.1.1 on 2025-04-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_participant_is_temporary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trigger',
            new_name='Strategy',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='triggers',
            new_name='strategies',
        ),
    ]
