# Generated by Django 5.1.1 on 2025-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_trigger_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='triggered_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
