# Generated by Django 5.1.1 on 2025-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_strategy_triggered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subtopics_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
