# Generated by Django 5.1.1 on 2025-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_conversation_subtopics_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary_posted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
