# Generated by Django 5.1.1 on 2025-05-02 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_conversation_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='chat.conversation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
