# Generated by Django 5.1.1 on 2025-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_conversation_duration_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
