# Generated by Django 5.1.1 on 2025-05-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_conversation_count_old_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='discussion',
        ),
        migrations.AddField(
            model_name='conversation',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chat.settings'),
        ),
        migrations.AddField(
            model_name='segment',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='chat.settings'),
        ),
    ]
