# Generated by Django 5.1.1 on 2025-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_settings_remove_conversation_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
